server:
  port: 8095

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize-mode: never

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.MySQLDialect

  liquibase:
    enabled: true
    change-log: db.changelog/db.changelog-master.xml

app:
  security:
    type: inMemory

